name: build
on:
  pull_request:
  push:
    branches: [ master ]
    tags:
      - .*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: npm install
      - run: npm run build
